openapi: 3.0.3
info:
  title: Interview Simulator API
  version: 1.0.0

paths:
  /auth/register:
    post:
      summary: Регистрация нового пользователя
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterRequest'
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          $ref: '#/components/responses/BadRequest'

  /auth/login:
    post:
      summary: Авторизация пользователя
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
      responses:
        '200':
          description: Успешная авторизация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /auth/refresh_token:
    post:
      summary: Обновление пары токенов (Access, Refresh)
      description: |
        В заголовке Authorization необходимо передать Refresh Token в формате `Bearer <token>`.
        Старый Refresh Token будет аннулирован, а в ответе придет новая пара токенов.
      tags:
        - Auth
      parameters:
        - name: Authorization
          in: header
          required: true
          description: "Refresh токен в формате 'Bearer <token>'"
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1Ni..."
      security:
        - bearerAuth: [ ]  # Указываем, что ждем токен в Authorization Header
      responses:
        '200':
          description: Токены успешно обновлены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /categories:
    get:
      summary: Список всех категорий
      tags:
        - Categories
      responses:
        '200':
          description: Список категорий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryDto'

  /courses:
    get:
      summary: Список всех курсов
      tags:
        - Courses
      parameters:
        - $ref: '#/components/parameters/CategoryIdQuery'
        - $ref: '#/components/parameters/LevelQuery'
      responses:
        '200':
          description: Список курсов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CourseDto'
  /admin/courses:
    post:
      summary: Создать новый курс
      tags:
        - Courses (Admin)
      security:
        - basicAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseCreateRequest'
      responses:
        '201':
          description: Курс успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseDto'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'

  /courses/{course_id}:
    get:
      summary: Получить подробности курса по ID
      tags:
        - Courses
      parameters:
        - $ref: '#/components/parameters/CourseIdPath'
      responses:
        '200':
          description: Детальная информация о курсе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseDetail'
        '404':
          $ref: '#/components/responses/NotFound'
  /admin/courses/{course_id}:
    put:
      summary: Обновить существующий курс
      tags:
        - Courses (Admin)
      security:
        - basicAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/CourseIdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseCreateRequest'
      responses:
        '200':
          description: Курс успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseDto'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Удалить курс
      tags:
        - Courses (Admin)
      security:
        - basicAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/CourseIdPath'
      responses:
        '204':
          description: Курс успешно удален
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /courses/{course_id}/attempt:
    post:
      summary: Начать новую попытку прохождения курса
      tags:
        - Attempts
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/CourseIdPath'
      responses:
        '201':
          description: Попытка успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttemptStartResponse'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /attempts/{attempt_id}/questions/{question_id}/answer:
    post:
      summary: Отправка ответа пользователя
      tags:
        - Attempts
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/AttemptIdPath'
        - $ref: '#/components/parameters/QuestionIdPath'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserAnswerRequest'
      responses:
        '202':
          description: Ответ сохранён и сейчас обрабатывается
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /attempts/{attempt_id}/finish:
    patch:
      summary: Завершение попытки
      tags:
        - Attempts
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/AttemptIdPath'
      responses:
        '200':
          description: Попытка успешно завершена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttemptDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /attempts/{attempt_id}:
    get:
      summary: Получить подробности попытки
      tags:
        - Attempts
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/AttemptIdPath'
      responses:
        '200':
          description: Детальная информация о попытке
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttemptDetail'
        '404':
          $ref: '#/components/responses/NotFound'

  /users/{user_id}/attempts:
    get:
      summary: История попыток пользователя
      tags:
        - Attempts
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Список всех попыток пользователя
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttemptSummary'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    basicAuth:
      type: http
      scheme: basic
      description: "Используется для административных действий (создание/редактирование контента)"

  parameters:
    CourseIdPath:
      name: course_id
      in: path
      required: true
      schema:
        type: integer
        format: int64
    AttemptIdPath:
      name: attempt_id
      in: path
      required: true
      schema:
        type: integer
        format: int64
    QuestionIdPath:
      name: question_id
      in: path
      required: true
      schema:
        type: integer
        format: int64
    CategoryIdQuery:
      name: category_id
      in: query
      required: false
      schema:
        type: integer
        format: int64
    LevelQuery:
      name: level
      in: query
      required: false
      schema:
        type: string
        enum:
          - junior
          - middle
          - senior

  responses:
    NotFound:
      description: Ресурс не найден
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseError'
    Unauthorized:
      description: Неавторизованный доступ
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseError'
    Forbidden:
      description: Недостаточно прав
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseError'
    BadRequest:
      description: Некорректный запрос
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseError'

  schemas:
    # --- AUTH & USER ---
    UserRegisterRequest:
      type: object
      required:
        - email
        - password
        - name
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          example: StrongPassword123
        name:
          type: string
          example: Иван Иванов
        birthdate:
          type: string
          format: date
          example: "1995-06-15"

    UserLoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    CourseCreateRequest:
      type: object
      required:
        - name
        - level
      properties:
        name:
          type: string
          example: "Advanced Java & Spring Boot"
        description:
          type: string
          example: "Курс для подготовки к Senior интервью"
        level:
          type: string
          enum: [ junior, middle, senior ]
        category_ids:
          type: array
          description: "Список ID категорий, к которым относится курс"
          items:
            type: integer
            format: int64
          example: [ 1, 5 ]
        question_ids:
          type: array
          description: "Список ID вопросов, входящих в курс"
          items:
            type: integer
            format: int64
          example: [ 101, 102, 105 ]

    AuthResponse:
      type: object
      required:
        - access_token
        - refresh_token
      properties:
        access_token:
          type: string
          example: jwt_token_here
        refresh_token:
          type: string
          example: jwt_token_here

    # --- CONTENT ---
    CategoryDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: SQL
        description:
          type: string
          example: Вопросы по базам данных

    CourseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 101
        name:
          type: string
          example: Backend Junior Interview
        description:
          type: string
        level:
          type: string
          enum:
            - junior
            - middle
            - senior
        categories:
          type: array
          items:
            $ref: '#/components/schemas/CategoryDto'

    QuestionDto:
      type: object
      properties:
        question_id:
          type: integer
          format: int64
          example: 1
        text:
          type: string
          example: Что делает LEFT JOIN?
        question_type:
          type: string
          enum:
            - objective
            - subjective
        complexity:
          type: integer
          example: 2

    CourseDetail:
      allOf:
        - $ref: '#/components/schemas/CourseDto'
        - type: object
          properties:
            questions:
              type: array
              items:
                $ref: '#/components/schemas/QuestionDto'

    # --- ATTEMPTS & ANSWERS ---
    AttemptSummary:
      type: object
      properties:
        attempt_id:
          type: integer
          format: int64
          example: 501
        course:
          $ref: '#/components/schemas/CourseDto'
        status:
          type: string
          enum:
            - in_progress
            - finished
            - abandoned
        timestamp_start:
          type: string
          format: date-time
        timestamp_end:
          type: string
          format: date-time
        overall_answer_score:
          type: integer
          example: 78
        overall_answer_feedback:
          type: string
        overall_speech_score:
          type: integer
          example: 78
        overall_speech_feedback:
          type: string

    AttemptStartResponse:
      type: object
      properties:
        attempt_id:
          type: integer
          format: int64
        course_id:
          type: integer
          format: int64
        status:
          type: string
          example: in_progress
        timestamp_start:
          type: string
          format: date-time
        questions:
          type: array
          items:
            $ref: '#/components/schemas/QuestionDto'

    AttemptDetail:
      allOf:
        - $ref: '#/components/schemas/AttemptSummary'
        - type: object
          properties:
            answers:
              type: array
              items:
                $ref: '#/components/schemas/UserAnswerResult'

    UserAnswerRequest:
      type: object
      required:
        - user_answer
        - audio_duration
      properties:
        user_answer:
          type: string
          format: binary
          description: Запись голоса (mp3)
        audio_duration:
          type: integer
          example: 115

    UserAnswerResponse:
      type: object
      properties:
        question_id:
          type: integer
          format: int64
        attempt_id:
          type: integer
          format: int64
        score:
          type: integer
          example: 8
        feedback:
          type: string
        created_at:
          type: string
          format: date-time

    UserAnswerResult:
      type: object
      properties:
        question_id:
          type: integer
          format: int64
        user_answer:
          type: string
        answer_score:
          type: integer
        speech_score:
          type: integer
        answer_feedback:
          type: string
        speech_feedback:
          type: string
        created_at:
          type: string
          format: date-time

    # --- COMMON ---
    BaseError:
      type: object
      properties:
        error:
          type: string
          example: Сообщение об ошибке