logging:
  level:
    root: INFO
    org.apache.hc.client5.http: DEBUG

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:nv+AyffVko53We9P8LPdOQT5d6UXvpNPWkec+0sZjb0=}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION:1800000} # 30 minutes
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION:86400000} # 1 day

http:
  common:
    maxConnectionTotal: 100
    maxConnectionPerRoute: 30
  ml:
    baseUrl: ${ML_URL:http://localhost:8000}
    connectTimeout: 5000 # 5 sec
    readTimeout: 240000 # 4 min

kafka:
  ml:
    topics: ${ML_KAFKA_TOPIC:answerEstimation}
    groupId: ${ML_KAFKA_GROUP_ID:answerEstimation.0}
    concurrency: ${ML_KAFKA_CONCURRENCY:1}

spring:
  application:
    name: interview-sim-backend
  liquibase:
    enabled: true
    change-log: classpath:migrations/changelog.yml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${ML_KAFKA_GROUP_ID:answerEstimation.0}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: "com.github.scripting.programming.language.interview_sim_backend.dto"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool-InterviewSim
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000 # Как долго соединение может висеть без дела перед удалением (5 минут)
      max-lifetime: 600000  # Максимальное время жизни соединения (10 минут)
      # Сколько ждать получения соединения из пула перед броском исключения (30 секунд)
      connection-timeout: 30000
      validation-timeout: 3000 # Время на проверку того, что соединение живо
      leak-detection-threshold: 5000 # Порог для обнаружения утечки соединения
      register-mbeans: false
    jpa:
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc.batch_size: 25
          order_inserts: true
          order_updates: true
          format_sql: true